### ISSUE TITLE
JSON file is empty

### ISSUE THREAD

**Issue by gsk1692** [kremso/dmoz-parser#5]
Hello,

I tried the command line usage and the sample.py method. The output JSON file is empty. 

Is it because the RDF file has changed the structure over time or something? Please consider the issue and respond at the earliest.

**Comment by kremso** [comment]
Hi Gokul, I haven't touched the code in years, it's very likely that the format has changed in the meantime.

**Comment by gsk1692** [comment]
Ohh...! Ok... Do u have the old RDF file which you were using? Maybe that will still work with the format... I just need the list of topics from DMOZ....

**Comment by kremso** [comment]
Sorry, I don't have the files anymore.

**Comment by gsk1692** [comment]
Ok... thank you for the response...
